version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing dependencies...
      - mvn clean install -DskipTests=true

  build:
    commands:
      - echo Build started on `date`
      - mvn package -DskipTests=true

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.jar
  discard-paths: yes

