version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: my-postgres-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Elimama_234
    ports:
      - "5432:5432"